### ISSUE TITLE
Error on Import

### ISSUE THREAD

**Issue by zilch42** [TutteInstitute/fast_hdbscan#1]
Hi there, I'm getting an error trying to import HDBSCAN from fast_hdbscan

`from fast_hdbscan import HDBSCAN`

```
---------------------------------------------------------------------------
TypingError                               Traceback (most recent call last)
Cell In[1], line 10
      8 from sklearn.feature_extraction.text import CountVectorizer
      9 from umap import UMAP
---> 10 from fast_hdbscan import HDBSCAN
     11 import pickle
     12 import sys

File [c:\Users\abb064\AppData\Local\miniconda3\envs\csiro-horizon-scanning39\lib\site-packages\fast_hdbscan\__init__.py:7](file:///C:/Users/abb064/AppData/Local/miniconda3/envs/csiro-horizon-scanning39/lib/site-packages/fast_hdbscan/__init__.py:7)
      5 random_state = np.random.RandomState(42)
      6 random_data = random_state.random(size=(100, 3))
----> 7 HDBSCAN(allow_single_cluster=True).fit(random_data)
      8 HDBSCAN(cluster_selection_method="leaf").fit(random_data)
     10 __all__ = ["HDBSCAN", "fast_hdbscan"]

File [c:\Users\abb064\AppData\Local\miniconda3\envs\csiro-horizon-scanning39\lib\site-packages\fast_hdbscan\hdbscan.py:217](file:///C:/Users/abb064/AppData/Local/miniconda3/envs/csiro-horizon-scanning39/lib/site-packages/fast_hdbscan/hdbscan.py:217), in HDBSCAN.fit(self, X, y, **fit_params)
    207     clean_data = X
    209 kwargs = self.get_params()
    211 (
    212     self.labels_,
    213     self.probabilities_,
    214     self._single_linkage_tree,
    215     self._condensed_tree,
    216     self._min_spanning_tree,
--> 217 ) = fast_hdbscan(clean_data, return_trees=True, **kwargs)
    219 self._condensed_tree = to_numpy_rec_array(self._condensed_tree)
    221 if not self._all_finite:
    222     # remap indices to align with original data in the case of non-finite entries.

File [c:\Users\abb064\AppData\Local\miniconda3\envs\csiro-horizon-scanning39\lib\site-packages\fast_hdbscan\hdbscan.py:149](file:///C:/Users/abb064/AppData/Local/miniconda3/envs/csiro-horizon-scanning39/lib/site-packages/fast_hdbscan/hdbscan.py:149), in fast_hdbscan(data, min_samples, min_cluster_size, cluster_selection_method, allow_single_cluster, return_trees)
    147 sklearn_tree = KDTree(data)
    148 numba_tree = kdtree_to_numba(sklearn_tree)
--> 149 edges = parallel_boruvka(
    150     numba_tree, min_samples=min_cluster_size if min_samples is None else min_samples
    151 )
    152 sorted_mst = edges[np.argsort(edges.T[2])]
    153 linkage_tree = mst_to_linkage_tree(sorted_mst)

File [c:\Users\abb064\AppData\Local\miniconda3\envs\csiro-horizon-scanning39\lib\site-packages\fast_hdbscan\boruvka.py:270](file:///C:/Users/abb064/AppData/Local/miniconda3/envs/csiro-horizon-scanning39/lib/site-packages/fast_hdbscan/boruvka.py:270), in parallel_boruvka(tree, min_samples)
    267 while n_components > 1:
    268     candidate_distances, candidate_indices = boruvka_tree_query(tree, node_components, point_components,
    269                                                                 core_distances)
--> 270     new_edges = merge_components(components_disjoint_set, candidate_indices, candidate_distances, point_components)
    271     update_component_vectors(tree, components_disjoint_set, node_components, point_components)
    273     edges = np.vstack((edges, new_edges))

File [c:\Users\abb064\AppData\Local\miniconda3\envs\csiro-horizon-scanning39\lib\site-packages\numba\core\dispatcher.py:468](file:///C:/Users/abb064/AppData/Local/miniconda3/envs/csiro-horizon-scanning39/lib/site-packages/numba/core/dispatcher.py:468), in _DispatcherBase._compile_for_args(self, *args, **kws)
    464         msg = (f"{str(e).rstrip()} \n\nThis error may have been caused "
    465                f"by the following argument(s):\n{args_str}\n")
    466         e.patch_message(msg)
--> 468     error_rewrite(e, 'typing')
    469 except errors.UnsupportedError as e:
    470     # Something unsupported is present in the user code, add help info
    471     error_rewrite(e, 'unsupported_error')
...
File ".[.\..\..\..\..\AppData\Local\miniconda3\envs\csiro-horizon-scanning39\lib\site-packages\fast_hdbscan\boruvka.py](https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/abb064/OneDrive%20-%20CSIRO/AppData/Local/miniconda3/envs/csiro-horizon-scanning39/lib/site-packages/fast_hdbscan/boruvka.py)", line 9:
def merge_components(disjoint_set, candidate_neighbors, candidate_neighbor_distances, point_components):
    component_edges = {0: (0, np.int32(1), np.float32(0.0)) for i in range(0)}
```

Python 3.9.16

**Comment by lmcinnes** [comment]
It looks as if numba is balking at some type issues, but it is not clear to
me what those could be from the error. This has worked acceptably on a few
different machines and configurations I tried, so it isn't the default
state of things.

What version of numba are you using?

**Comment by zilch42** [comment]
Numba 0.56.4

Here is my whole environment 
```
# Name                    Version                   Build  Channel
aiofiles                  22.1.0                   pypi_0    pypi
aiohttp                   3.8.4                    pypi_0    pypi
aiosignal                 1.3.1                    pypi_0    pypi
aiosqlite                 0.18.0                   pypi_0    pypi
anyio                     3.6.2                    pypi_0    pypi
argon2-cffi               21.3.0                   pypi_0    pypi
argon2-cffi-bindings      21.2.0                   pypi_0    pypi
arrow                     1.2.3                    pypi_0    pypi
asttokens                 2.2.1                    pypi_0    pypi
async-timeout             4.0.2                    pypi_0    pypi
attrs                     22.2.0                   pypi_0    pypi
babel                     2.12.1                   pypi_0    pypi
backcall                  0.2.0                    pypi_0    pypi
beautifulsoup4            4.11.2                   pypi_0    pypi
bertopic                  0.14.1                   pypi_0    pypi
bleach                    6.0.0                    pypi_0    pypi
blis                      0.7.9                    pypi_0    pypi
bzip2                     1.0.8                h8ffe710_4    conda-forge
ca-certificates           2022.12.7            h5b45459_0    conda-forge
cachetools                5.3.0                    pypi_0    pypi
catalogue                 2.0.8                    pypi_0    pypi
certifi                   2022.12.7                pypi_0    pypi
cffi                      1.15.1                   pypi_0    pypi
charset-normalizer        3.1.0                    pypi_0    pypi
click                     8.1.3                    pypi_0    pypi
colorama                  0.4.6                    pypi_0    pypi
comm                      0.1.2                    pypi_0    pypi
confection                0.0.4                    pypi_0    pypi
contourpy                 1.0.7                    pypi_0    pypi
cycler                    0.11.0                   pypi_0    pypi
cymem                     2.0.7                    pypi_0    pypi
cython                    0.29.33                  pypi_0    pypi
cytoolz                   0.12.1                   pypi_0    pypi
debugpy                   1.6.6                    pypi_0    pypi
decorator                 5.1.1                    pypi_0    pypi
defusedxml                0.7.1                    pypi_0    pypi
dnspython                 2.3.0                    pypi_0    pypi
exceptiongroup            1.1.0                    pypi_0    pypi
executing                 1.2.0                    pypi_0    pypi
fast-hdbscan              0.1.0                    pypi_0    pypi
fastjsonschema            2.16.3                   pypi_0    pypi
filelock                  3.9.0                    pypi_0    pypi
fonttools                 4.39.0                   pypi_0    pypi
fqdn                      1.5.1                    pypi_0    pypi
frozenlist                1.3.3                    pypi_0    pypi
hdbscan                   0.8.29                   pypi_0    pypi
huggingface-hub           0.13.0                   pypi_0    pypi
idna                      3.4                      pypi_0    pypi
importlib-metadata        6.0.0                    pypi_0    pypi
importlib-resources       5.12.0                   pypi_0    pypi
iniconfig                 2.0.0                    pypi_0    pypi
ipykernel                 6.21.3                   pypi_0    pypi
ipython                   8.11.0                   pypi_0    pypi
ipython-genutils          0.2.0                    pypi_0    pypi
ipywidgets                8.0.4                    pypi_0    pypi
isoduration               20.11.0                  pypi_0    pypi
jedi                      0.18.2                   pypi_0    pypi
jellyfish                 0.9.0                    pypi_0    pypi
jinja2                    3.1.2                    pypi_0    pypi
joblib                    1.2.0                    pypi_0    pypi
json5                     0.9.11                   pypi_0    pypi
jsonpointer               2.3                      pypi_0    pypi
jsonschema                4.17.3                   pypi_0    pypi
jupyter-client            8.0.3                    pypi_0    pypi
jupyter-core              5.2.0                    pypi_0    pypi
jupyter-events            0.6.3                    pypi_0    pypi
jupyter-server            2.4.0                    pypi_0    pypi
jupyter-server-fileid     0.8.0                    pypi_0    pypi
jupyter-server-terminals  0.4.4                    pypi_0    pypi
jupyter-server-ydoc       0.6.1                    pypi_0    pypi
jupyter-ydoc              0.2.2                    pypi_0    pypi
jupyterlab                3.6.1                    pypi_0    pypi
jupyterlab-pygments       0.2.2                    pypi_0    pypi
jupyterlab-server         2.20.0                   pypi_0    pypi
jupyterlab-widgets        3.0.5                    pypi_0    pypi
kiwisolver                1.4.4                    pypi_0    pypi
langcodes                 3.3.0                    pypi_0    pypi
libffi                    3.4.2                h8ffe710_5    conda-forge
libsqlite                 3.40.0               hcfcfb64_0    conda-forge
libzlib                   1.2.13               hcfcfb64_4    conda-forge
llvmlite                  0.39.1                   pypi_0    pypi
loguru                    0.6.0                    pypi_0    pypi
markupsafe                2.1.2                    pypi_0    pypi
matplotlib                3.7.1                    pypi_0    pypi
matplotlib-inline         0.1.6                    pypi_0    pypi
mistune                   2.0.5                    pypi_0    pypi
multidict                 6.0.4                    pypi_0    pypi
murmurhash                1.0.9                    pypi_0    pypi
nbclassic                 0.5.3                    pypi_0    pypi
nbclient                  0.7.2                    pypi_0    pypi
nbconvert                 7.2.9                    pypi_0    pypi
nbformat                  5.7.3                    pypi_0    pypi
nest-asyncio              1.5.6                    pypi_0    pypi
networkx                  3.0                      pypi_0    pypi
nltk                      3.8.1                    pypi_0    pypi
notebook                  6.5.3                    pypi_0    pypi
notebook-shim             0.2.2                    pypi_0    pypi
numba                     0.56.4                   pypi_0    pypi
numpy                     1.23.5                   pypi_0    pypi
openai                    0.27.1                   pypi_0    pypi
openssl                   3.0.8                hcfcfb64_0    conda-forge
packaging                 23.0                     pypi_0    pypi
pandas                    1.5.3                    pypi_0    pypi
pandocfilters             1.5.0                    pypi_0    pypi
parso                     0.8.3                    pypi_0    pypi
pathy                     0.10.1                   pypi_0    pypi
pickleshare               0.7.5                    pypi_0    pypi
pillow                    9.4.0                    pypi_0    pypi
pip                       23.0.1             pyhd8ed1ab_0    conda-forge
platformdirs              3.1.0                    pypi_0    pypi
plotly                    5.13.1                   pypi_0    pypi
pluggy                    1.0.0                    pypi_0    pypi
preshed                   3.0.8                    pypi_0    pypi
prometheus-client         0.16.0                   pypi_0    pypi
prompt-toolkit            3.0.38                   pypi_0    pypi
psutil                    5.9.4                    pypi_0    pypi
pure-eval                 0.2.2                    pypi_0    pypi
pycparser                 2.21                     pypi_0    pypi
pydantic                  1.10.6                   pypi_0    pypi
pygments                  2.14.0                   pypi_0    pypi
pymongo                   4.3.3                    pypi_0    pypi
pynndescent               0.5.8                    pypi_0    pypi
pyparsing                 3.0.9                    pypi_0    pypi
pyphen                    0.13.2                   pypi_0    pypi
pyrsistent                0.19.3                   pypi_0    pypi
pytest                    7.2.2                    pypi_0    pypi
python                    3.9.16          h4de0772_0_cpython    conda-forge
python-dateutil           2.8.2                    pypi_0    pypi
python-dotenv             1.0.0                    pypi_0    pypi
python-json-logger        2.0.7                    pypi_0    pypi
pytz                      2022.7.1                 pypi_0    pypi
pywin32                   305                      pypi_0    pypi
pywinpty                  2.0.10                   pypi_0    pypi
pyyaml                    6.0                      pypi_0    pypi
pyzmq                     25.0.0                   pypi_0    pypi
regex                     2022.10.31               pypi_0    pypi
requests                  2.28.2                   pypi_0    pypi
rfc3339-validator         0.1.4                    pypi_0    pypi
rfc3986-validator         0.1.1                    pypi_0    pypi
river                     0.14.0                   pypi_0    pypi
scikit-learn              1.2.1                    pypi_0    pypi
scipy                     1.10.1                   pypi_0    pypi
send2trash                1.8.0                    pypi_0    pypi
sentence-transformers     2.2.2                    pypi_0    pypi
sentencepiece             0.1.97                   pypi_0    pypi
setuptools                67.5.1             pyhd8ed1ab_0    conda-forge
six                       1.16.0                   pypi_0    pypi
smart-open                6.3.0                    pypi_0    pypi
sniffio                   1.3.0                    pypi_0    pypi
soupsieve                 2.4                      pypi_0    pypi
spacy                     3.5.0                    pypi_0    pypi
spacy-legacy              3.0.12                   pypi_0    pypi
spacy-loggers             1.0.4                    pypi_0    pypi
srsly                     2.4.6                    pypi_0    pypi
stack-data                0.6.2                    pypi_0    pypi
tenacity                  8.2.2                    pypi_0    pypi
terminado                 0.17.1                   pypi_0    pypi
textacy                   0.12.0                   pypi_0    pypi
textblob                  0.17.1                   pypi_0    pypi
thinc                     8.1.9                    pypi_0    pypi
threadpoolctl             3.1.0                    pypi_0    pypi
tinycss2                  1.2.1                    pypi_0    pypi
tk                        8.6.12               h8ffe710_0    conda-forge
tokenizers                0.13.2                   pypi_0    pypi
tomli                     2.0.1                    pypi_0    pypi
toolz                     0.12.0                   pypi_0    pypi
topicmodeltuner           0.3.4                    pypi_0    pypi
torch                     1.13.1                   pypi_0    pypi
torchvision               0.14.1                   pypi_0    pypi
tornado                   6.2                      pypi_0    pypi
tqdm                      4.65.0                   pypi_0    pypi
traitlets                 5.9.0                    pypi_0    pypi
transformers              4.26.1                   pypi_0    pypi
typer                     0.7.0                    pypi_0    pypi
typing-extensions         4.5.0                    pypi_0    pypi
tzdata                    2022g                h191b570_0    conda-forge
ucrt                      10.0.22621.0         h57928b3_0    conda-forge
umap-learn                0.5.3                    pypi_0    pypi
uri-template              1.2.0                    pypi_0    pypi
urllib3                   1.26.14                  pypi_0    pypi
vc                        14.3                hb6edc58_10    conda-forge
vs2015_runtime            14.34.31931         h4c5c07a_10    conda-forge
wasabi                    1.1.1                    pypi_0    pypi
wcwidth                   0.2.6                    pypi_0    pypi
webcolors                 1.12                     pypi_0    pypi
webencodings              0.5.1                    pypi_0    pypi
websocket-client          1.5.1                    pypi_0    pypi
wheel                     0.38.4             pyhd8ed1ab_0    conda-forge
widgetsnbextension        4.0.5                    pypi_0    pypi
win32-setctime            1.1.0                    pypi_0    pypi
xz                        5.2.6                h8d14728_0    conda-forge
y-py                      0.5.9                    pypi_0    pypi
yarl                      1.8.2                    pypi_0    pypi
ypy-websocket             0.8.2                    pypi_0    pypi
zipp                      3.15.0                   pypi_0    pypi
```

**Comment by VolkerH** [comment]
Running into the same error. I have this additional error message:

```
TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Cannot unify DictType[int32,Tuple(int64, int32, float32)]<iv=None> and DictType[int64,Tuple(int64, int32, float32)]<iv=None> for 'closure__locals___dictcomp__v167__vphi36_0', defined at C:\Users\redacted\AppData\Local\pypoetry\Cache\virtualenvs\redacted\lib\site-packages\fast_hdbscan\boruvka.py (9)

File "..\..\..\AppData\Local\pypoetry\Cache\virtualenvs\redacted\lib\site-packages\fast_hdbscan\boruvka.py", line 9:
def merge_components(disjoint_set, candidate_neighbors, candidate_neighbor_distances, point_components):
    component_edges = {0: (0, np.int32(1), np.float32(0.0)) for i in range(0)}
```

Python 3.9.0
Numba 0.56.4

Seems like a int32 vs int64 in a dict key problem.
Any pointers?

**Comment by lmcinnes** [comment]
I'm hoping that as numpy and numba settle down with reagrd to the new APIs etc. that some of this will magically resolve itself ( I don't think this package does anything weird, or uses anything particularly specific/internal). For now I'll keep it as a "wait and see".
