### ISSUE TITLE
Feature request: Support for metric='precomputed'

### ISSUE THREAD

**Issue by RichieHakim** [TutteInstitute/fast_hdbscan#5]
I'm currently using vanilla HDBSCAN to cluster a precomputed sparse distance matrix being input as a `scipy.sparse.csr_matrix` object. I'm very eager to use fast_hdbscan due primarily to it's easier compilation requirements as I'm attempting to ship out a tool that uses hdbscan as a step in a pipeline.

Currently, I believe clustering on precomputed sparse distance matrices is not supported in fast_hdbscan. I think it would require the porting of some of the following functions:
- `hdbscan_._hdbscan_sparse_distance_matrix`
- `_hdbscan_reachability.sparse_mutual_reachability`
- `_hdbscan_linkage.label`

Unfortunately, I don't think I'm able to figure out how to implement this one myself. Though, I'm happy to help out in testing any PRs with basic implementations. 
Thank you for great package and I really hope I'll be able to use it soon!

**Comment by lmcinnes** [comment]
There are some quirks about sparse precomputed distance matrices that can
make things a little tricky for corner-cases. I'll see if I can get
something done though. I can't promise any timeframes.

**Comment by RichieHakim** [comment]
Thank you so much for looking into this. I am very motivated to help if you think it's possible to delegate anything. For what it's worth, this is how hdbscan is being used in the project I'm working on: [https://github.com/RichieHakim/ROICaT/blob/dev/roicat/tracking/clustering.py#L398]()

Perhaps bringing up the tricks/hacks that are being used to get desired behavior would be of interest. 1) I'm using a very custom sparse distance matrix as input. 2) Since the graph has multiple disjointed components, I need to add a fully connected node before clustering. 3) Since there are sample pairs that are known to be disconnected a priori, clusters containing these pairs ('pair violations') are split up by walking down the cutting distance until the pair violations are gone.

Playing with the `max_dist` doesn't help much here. Single linkage is a blessing and a curse it seems. If there was a way for the MST to be blind to any sample that would cause a violation as the tree is built up, that would be of significant utility for tracking software.

Thanks again, I'm a big fan of all your projects.

**Comment by RichieHakim** [comment]
@lmcinnes 
bumping this based on this conversation: https://github.com/scikit-learn-contrib/hdbscan/issues/299.

I will look into existing semi-supervised methods for vanilla HDBSCAN, and I will look into approaches to recover / convert to embedding vectors from sparse distance matrices so that we can try fast_hdbscan. If there is a way to achieve both in one library, we are very interested. Please let me know if either would benefit from further conversation or resources. Thanks again for these amazing resources.

**Comment by aselimc** [comment]
Hello, on a large number of samples (N > 1 000 000) with 3D data (pointcloud) I am receiving the following error when using semi-supervised (with or without vn option same error)

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/canakcia/miniconda3/envs/l3ps/lib/python3.9/site-packages/fast_hdbscan/hdbscan.py", line 316, in fit
    ) = fast_hdbscan(
  File "/home/canakcia/miniconda3/envs/l3ps/lib/python3.9/site-packages/fast_hdbscan/hdbscan.py", line 206, in fast_hdbscan
    selected_clusters = extract_clusters_bcubed(
  File "/home/canakcia/miniconda3/envs/l3ps/lib/python3.9/site-packages/numba/core/dispatcher.py", line 423, in _compile_for_args
    error_rewrite(e, 'typing')
  File "/home/canakcia/miniconda3/envs/l3ps/lib/python3.9/site-packages/numba/core/dispatcher.py", line 364, in error_rewrite
    raise e.with_traceback(None)
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Failed in nopython mode pipeline (step: nopython frontend)
Cannot unify DictType[float64,int64]<iv=None> and DictType[int64,int64]<iv=None> for 'closure__locals___dictcomp__v267__vphi18_0', defined at /home/canakcia/miniconda3/envs/l3ps/lib/python3.9/site-packages/fast_hdbscan/cluster_trees.py (357)

File "../../../../miniconda3/envs/l3ps/lib/python3.9/site-packages/fast_hdbscan/cluster_trees.py", line 357:
def score_condensed_tree_nodes_bcubed(cluster_elements, label_indices): 
    <source elided>
    label_values = label_indices.values()
    label_counts = {0: 0 for i in range(0)}
    ^

During: typing of assignment at /home/canakcia/miniconda3/envs/l3ps/lib/python3.9/site-packages/fast_hdbscan/cluster_trees.py (357)

File "../../../../miniconda3/envs/l3ps/lib/python3.9/site-packages/fast_hdbscan/cluster_trees.py", line 357:
def score_condensed_tree_nodes_bcubed(cluster_elements, label_indices): 
    <source elided>
    label_values = label_indices.values()
    label_counts = {0: 0 for i in range(0)}
    ^

During: resolving callee type: type(CPUDispatcher(<function score_condensed_tree_nodes_bcubed at 0x7f8c6871e3a0>))
During: typing of call at /home/canakcia/miniconda3/envs/l3ps/lib/python3.9/site-packages/fast_hdbscan/cluster_trees.py (408)

During: resolving callee type: type(CPUDispatcher(<function score_condensed_tree_nodes_bcubed at 0x7f8c6871e3a0>))
During: typing of call at /home/canakcia/miniconda3/envs/l3ps/lib/python3.9/site-packages/fast_hdbscan/cluster_trees.py (415)

During: resolving callee type: type(CPUDispatcher(<function score_condensed_tree_nodes_bcubed at 0x7f8c6871e3a0>))
During: typing of call at /home/canakcia/miniconda3/envs/l3ps/lib/python3.9/site-packages/fast_hdbscan/cluster_trees.py (408)


File "../../../../miniconda3/envs/l3ps/lib/python3.9/site-packages/fast_hdbscan/cluster_trees.py", line 408:
def extract_clusters_bcubed(condensed_tree, cluster_tree, label_indices, allow_virtual_nodes=False, allow_single_cluster=False):
    <source elided>
            stability_node_scores[node] = 0.0
        bcubed_node_scores = score_condensed_tree_nodes_bcubed(cluster_elements, label_indices)
```

**Comment by RichieHakim** [comment]
@lmcinnes new PR for this feature request https://github.com/TutteInstitute/fast_hdbscan/pull/47

(still finishing up the cannot-link constraints implementation, should be coming soon)
